/**
 * File picker + drag-and-drop, wired directly to the real normalisation
 * pipeline in src/supabase/storageUpload.ts (ADR-0002). Deliberately does
 * NOT gate on file extension — decode failure (e.g. HEIC in Chrome) and
 * oversize are surfaced using that module's own error messages verbatim,
 * since those messages were written to be shown directly to a user.
 *
 * `code` must be a Room code already generated by the caller (HomeScreen) —
 * the pipeline uploads under `rooms/<code>/…` before the Room row exists,
 * so the code is the join key between "picked a file" and "created a Room".
 *
 * Visually this is the recessed art well in the box lid (see theme.css):
 * once a photo is in, it fills the well as the box art, and the re-pick
 * prompt only surfaces on hover so the picture stays the point.
 */

import { useCallback, useRef, useState, type ChangeEvent, type DragEvent, type ReactNode } from "react";
import { getPublicImageUrl, normaliseAndUploadImage } from "../supabase/storageUpload";

export type UploadedImage = {
  readonly path: string;
  readonly width: number;
  readonly height: number;
};

export type UploadFormProps = {
  readonly code: string;
  readonly uploaded: UploadedImage | null;
  readonly onUploaded: (image: UploadedImage) => void;
  /** Cut-line preview drawn over the box art (see PuzzlePreview). */
  readonly overlay?: ReactNode;
};

type Phase = "idle" | "working" | "error";

export function UploadForm({ code, uploaded, onUploaded, overlay }: UploadFormProps) {
  const [phase, setPhase] = useState<Phase>("idle");
  const [statusText, setStatusText] = useState<string>("");
  const [error, setError] = useState<string | null>(null);
  const [dragOver, setDragOver] = useState(false);
  const inputRef = useRef<HTMLInputElement | null>(null);

  const handleFile = useCallback(
    async (file: File) => {
      setPhase("working");
      setError(null);
      setStatusText("Preparing the photo…");
      try {
        const { path } = await normaliseAndUploadImage(file, code);
        setStatusText("Almost there…");
        const { width, height } = await loadImageDimensions(path);
        setPhase("idle");
        setStatusText("");
        onUploaded({ path, width, height });
      } catch (err) {
        setPhase("error");
        setStatusText("");
        setError(err instanceof Error ? err.message : "That photo couldn't be uploaded. Try another one.");
      }
    },
    [code, onUploaded],
  );

  const onInputChange = (e: ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) void handleFile(file);
    e.target.value = "";
  };

  const onDrop = (e: DragEvent<HTMLButtonElement>) => {
    e.preventDefault();
    setDragOver(false);
    const file = e.dataTransfer.files?.[0];
    if (file) void handleFile(file);
  };

  const working = phase === "working";
  const previewUrl = uploaded ? getPublicImageUrl(uploaded.path) : null;

  // The well takes the photo's own shape once there is one, so the box art is
  // the whole picture — the puzzle is cut from every pixel, and a cropped
  // preview would promise a different puzzle than the one you get. Clamped so
  // a panorama or a tall phone shot still leaves a usable lid.
  const wellAspect = uploaded
    ? Math.min(2, Math.max(0.8, uploaded.width / uploaded.height))
    : undefined;

  return (
    <div>
      <button
        type="button"
        style={wellAspect ? { aspectRatio: String(wellAspect) } : undefined}
        className={`well${dragOver ? " well--over" : ""}`}
        onClick={() => inputRef.current?.click()}
        onDragOver={(e) => {
          e.preventDefault();
          setDragOver(true);
        }}
        onDragLeave={() => setDragOver(false)}
        onDrop={onDrop}
        aria-label={uploaded ? "Replace the photo" : "Choose a photo"}
      >
        {previewUrl && !working && (
          <>
            <img className="well__img" src={previewUrl} alt="" aria-hidden="true" />
            {overlay}
          </>
        )}

        <span className={`well__body${previewUrl && !working ? " well__body--over-img" : ""}`}>
          {working ? (
            <>
              <span className="well__spinner" aria-hidden="true" />
              <span className="well__sub" style={{ color: "var(--chip)" }}>
                {statusText}
              </span>
            </>
          ) : previewUrl ? (
            <span className="well__cue">Replace photo</span>
          ) : (
            <>
              <span className="well__cue">Drop a photo here</span>
              <span className="well__sub">or click to choose one</span>
            </>
          )}
        </span>
      </button>

      <input
        ref={inputRef}
        type="file"
        accept="image/*"
        onChange={onInputChange}
        style={{ display: "none" }}
      />

      {error && <p className="note">{error}</p>}
    </div>
  );
}

async function loadImageDimensions(path: string): Promise<{ width: number; height: number }> {
  const url = getPublicImageUrl(path);
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve({ width: img.naturalWidth, height: img.naturalHeight });
    img.onerror = () => reject(new Error("The photo uploaded but couldn't be read back. Try again."));
    img.src = url;
  });
}
