/**
 * File picker + drag-and-drop, wired directly to the real normalisation
 * pipeline in src/supabase/storageUpload.ts (ADR-0002). Deliberately does
 * NOT gate on file extension — decode failure (e.g. HEIC in Chrome) and
 * oversize are surfaced using that module's own error messages verbatim,
 * since those messages were written to be shown directly to a user.
 *
 * `code` must be a Room code already generated by the caller (HomeScreen) —
 * the pipeline uploads to `rooms/<code>/image` before the Room row exists,
 * so the code is the join key between "picked a file" and "created a Room".
 */

import { useCallback, useRef, useState, type ChangeEvent, type CSSProperties, type DragEvent } from "react";
import { getPublicImageUrl, normaliseAndUploadImage } from "../supabase/storageUpload";

export type UploadedImage = {
  readonly path: string;
  readonly width: number;
  readonly height: number;
};

export type UploadFormProps = {
  readonly code: string;
  readonly uploaded: UploadedImage | null;
  readonly onUploaded: (image: UploadedImage) => void;
};

type Phase = "idle" | "working" | "error";

export function UploadForm({ code, uploaded, onUploaded }: UploadFormProps) {
  const [phase, setPhase] = useState<Phase>("idle");
  const [statusText, setStatusText] = useState<string>("");
  const [error, setError] = useState<string | null>(null);
  const [dragOver, setDragOver] = useState(false);
  const inputRef = useRef<HTMLInputElement | null>(null);

  const handleFile = useCallback(
    async (file: File) => {
      setPhase("working");
      setError(null);
      setStatusText("Preparing image…");
      try {
        const { path } = await normaliseAndUploadImage(file, code);
        setStatusText("Finishing up…");
        const { width, height } = await loadImageDimensions(code);
        setPhase("idle");
        setStatusText("");
        onUploaded({ path, width, height });
      } catch (err) {
        setPhase("error");
        setStatusText("");
        setError(err instanceof Error ? err.message : "Something went wrong uploading that image.");
      }
    },
    [code, onUploaded],
  );

  const onInputChange = (e: ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) void handleFile(file);
    e.target.value = "";
  };

  const onDrop = (e: DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setDragOver(false);
    const file = e.dataTransfer.files?.[0];
    if (file) void handleFile(file);
  };

  return (
    <div>
      <div
        style={{
          ...styles.dropzone,
          ...(dragOver ? styles.dropzoneActive : null),
        }}
        onDragOver={(e) => {
          e.preventDefault();
          setDragOver(true);
        }}
        onDragLeave={() => setDragOver(false)}
        onDrop={onDrop}
        onClick={() => inputRef.current?.click()}
        role="button"
        tabIndex={0}
        onKeyDown={(e) => {
          if (e.key === "Enter" || e.key === " ") inputRef.current?.click();
        }}
      >
        <input
          ref={inputRef}
          type="file"
          accept="image/*"
          onChange={onInputChange}
          style={{ display: "none" }}
        />
        {phase === "working" ? (
          <p style={styles.hint}>{statusText || "Working…"}</p>
        ) : uploaded ? (
          <p style={styles.hint}>Image ready. Click or drop to replace it.</p>
        ) : (
          <p style={styles.hint}>Drop an image here, or click to choose one</p>
        )}
      </div>
      {error && <p style={styles.error}>{error}</p>}
    </div>
  );
}

async function loadImageDimensions(code: string): Promise<{ width: number; height: number }> {
  const url = getPublicImageUrl(code);
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve({ width: img.naturalWidth, height: img.naturalHeight });
    img.onerror = () => reject(new Error("Uploaded image could not be reloaded to measure it."));
    img.src = url;
  });
}

const styles: Record<string, CSSProperties> = {
  dropzone: {
    border: "2px dashed #3a3f4b",
    borderRadius: 10,
    padding: "28px 20px",
    textAlign: "center",
    cursor: "pointer",
    background: "#171a21",
  },
  dropzoneActive: {
    borderColor: "#4363d8",
    background: "#1a2033",
  },
  hint: {
    margin: 0,
    color: "#c3c7d1",
    fontSize: 14,
  },
  error: {
    marginTop: 8,
    color: "#e6194b",
    fontSize: 13,
  },
};
